# Generated by Django 3.1.3 on 2020-11-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
