site_name: UPSkilling
site_url: https://huyuhui001.github.io/mySite/
repo_name: "huyuhui001/mySite"
repo_url: https://github.com/huyuhui001/mySite
edit_uri: edit/main/docs/

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


theme:
  name: 'material'
  logo: assets/logo.jpg
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.instant
  - navigation.top
 
  palette:
    primary: 'teal'
    accent: 'green'

  include_sidebar: true

plugins:
  - search
  - minify:
      minify_html: true

extra_css: [extra.css]

nav:
- UPSkilling: 
  - Welcome: index.md
  - About: about.md
- Linux:
  - Index: linux/index.md
  - Linux SRE:
    - Linux Fundamentals: linux/SRE/01-fundamentals.md
    - File System: linux/SRE/02-filesystem.md
    - Identity & Security: linux/SRE/03-identity-security.md
  - SUSE Linux Administration: 
    - Linux File System Overview: linux/Administration/01.md
    - Useful Commands: linux/Administration/02.md
    - Shell: linux/Administration/03.md
  - SUSE Enterprise Storage Foundation: 
    - SUSE Enterprise Storage Foundation: linux/SES/linux_ses_memo.md
    - SUSE Enterprise Storage Basic Operation: linux/SES/linux_ses_demo.md
- Kubernetes:
  - Index: k8s/index.md
  - Installation:
    - Single Node Installation: k8s/installation/single-local.md
    - Multiple Nodes Installation: k8s/installation/multiple-local.md
    - Installation on Aliyun ECS: k8s/installation/aliyun-ubuntu.md
  - Docker:
    - Fundamentals: k8s/foundamentals/docker.md
  - Foundamentals:
    - Memo: k8s/foundamentals/memo.md
    - Overview: k8s/foundamentals/overview.md
    - kubectl basics: k8s/foundamentals/basics.md
  - Core Kubernetes:
    - Pod: k8s/foundamentals/pod.md
    - Deployment: k8s/foundamentals/deployment.md
    - Service: k8s/foundamentals/service.md
  - Application Modeling:
    - Namespace: k8s/foundamentals/namespace.md
    - StatefulSet: k8s/foundamentals/statefulset.md
    - DaemonSet: k8s/foundamentals/daemonset.md
    - Job and Cronjob: k8s/foundamentals/job.md
    - Configuration: k8s/foundamentals/configuration.md
    - Secrets: k8s/foundamentals/secrets.md
    - Persistence: k8s/foundamentals/persistence.md
    - Role Based Access Control (RBAC): k8s/foundamentals/rbac.md
    - Ingress: k8s/foundamentals/ingress.md
  - Advanced Kubernetes:
    - Scheduling: k8s/foundamentals/scheduling.md
    - Horizontal Pod Autoscaling: k8s/foundamentals/hpa.md
    - Policy: k8s/foundamentals/policy.md
    - Network Policy: k8s/foundamentals/networkpolicy.md
    - Cluster Management: k8s/foundamentals/clustermgt.md
  - Operating Kubernetes:
    - Troubleshooting: k8s/foundamentals/troubleshooting.md
    - Health Check: k8s/foundamentals/healthcheck.md
    - Helming: k8s/foundamentals/helming.md
  - Case Study:
    - Operations on Resources: k8s/foundamentals/casestudy-operation-resources.md
    - Health Check: k8s/foundamentals/casestudy-health-check.md
    - Calico Installation: k8s/foundamentals/casestudy-calico.md
    - Kyma: k8s/foundamentals/kyma.md
  - Demos:
    - Build CAP application on Kyma: k8s/demo/cap_on_kyma.md
- Python:
  - Index: python/index.md
  - Python基础:
    - 安装: python/Foundation/ch00.md
    - 语言基础: python/Foundation/ch01.md
    - 打包和拆包: python/Foundation/ch02.md
    - 函数及文件: python/Foundation/ch03.md
    - 面向对象概念: python/Foundation/ch04.md
    - 面向对象特性: python/Foundation/ch05.md
    - 数据结构和算法: python/Foundation/Algorithms.md
  - Python数据分析基础:
    - NumPy基础: python/DataAnalysis/ch01.md
    - NumPy进阶: python/DataAnalysis/ch10.md
    - Pandas入门: python/DataAnalysis/ch02.md
    - 数据载入、存储及文件格式: python/DataAnalysis/ch03.md
    - 数据清洗与准备: python/DataAnalysis/ch04.md
    - 数据规整：连接、联合与重塑: python/DataAnalysis/ch05.md
    - 绘图与可视化: python/DataAnalysis/ch06.md
    - 数据聚合与分组操作: python/DataAnalysis/ch07.md
    - 时间序列: python/DataAnalysis/ch08.md
    - 高阶pandas: python/DataAnalysis/ch09.md
    - Python建模库介绍: python/DataAnalysis/ch11.md
  - Demos:
    - 选课系统: python/Demo/CourseSystem.md

