site_name: ZERO-ONE-ZERO
site_url: https://huyuhui001.github.io/mySite/index.html
nav:
        - Home: index.md
        - Linux: linux.md
        - Python: python.md
        - About: about.md
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'Deep blue'
