site_name: MEMO
site_url: https://huyuhui001.github.io/mySite/
repo_name: "huyuhui001/mySite"
repo_url: https://github.com/huyuhui001/mySite
edit_uri: edit/main/docs/

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


theme:
  name: 'material'
  logo: assets/logo.jpg
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.instant
  - navigation.sections
 
  palette:
    primary: 'teal'
    accent: 'green'

  include_sidebar: true

plugins:
  - search

nav:
- Linux:
    - SUSE Linux Administration: linux/Administration/linux_admin.md
    - SUSE Enterprise Storage Foundation: linux/SES/linux_ses.md
- Python:
    - Python Foundamentals: python/Foundation/python_foundation_index.md
    - Data Analysis: python/DataAnalysis/python_data_analysis_index.md
    - Demos: python/Demo/python_demo_index.md
- Kubernetes:
    - Installation:
        - Single Node Installation: k8s/installation/single-local.md
        - Multiple Nodes Installation: k8s/installation/multiple-local.md
        - Installation on Aliyun openSUSE: k8s/installation/aliyun-opensuse.md
        - Installation on Aliyun Ubuntu: k8s/installation/aliyun-ubuntu.md
    - Foundamentals:
        - kubectl basics: k8s/foundamentals/basics.md
        - Work on pod: k8s/foundamentals/pod.md
        - Deployment: k8s/foundamentals/deployment.md
        - Expose application: k8s/foundamentals/expose.md
        - Persistence: k8s/foundamentals/persistence.md
        - ConfigMaps and Secrets: k8s/foundamentals/configmaps.md
        - Ingress: k8s/foundamentals/ingress.md
        - StatefulSet: k8s/foundamentals/statefulset.md
        - Network Policy: k8s/foundamentals/networkpolicy.md
        - Helming: k8s/foundamentals/helming.md
- About: about.md

